### ISSUE TITLE
history - response summary delete action, minimal error handlers

### ISSUE THREAD

**Issue by wrenr** [ucla/ohmageX#708] opened 2015-07-10 18:44 UTC
Add delete button, deletes the response from the server, bare bones error handlers

**Comment by wrenr** [comment] 2015-08-11 20:03
@hongsudt I am sending the following request and the server is returning the error "Authentication Credentials were not provided." 

Mobile username and password credentials were provided. Network details:

    Request URL:https://test.mobilizingcs.org/app/survey_response/delete
    Request Method:POST
    Content-Type:application/x-www-form-urlencoded; charset=UTF-8

    Form Data:
    client:ohmagex-browser
    campaign_urn:urn:campaign:tpp:internal:ctrance:eqissurveys16
    survey_key:dec9ddfa-86f0-4d26-b64a-f5a2d47e683e
    user: [mobile username]
    password: [mobile hashed password]

**Comment by stevenolen** [comment] 2015-08-11 20:46
@wrenr, the server doesn't currently support survey_response/delete with any auth except auth_token.  This is likely a hold over from long ago when it was intended that users not manage data from mobile devices.  @hongsudt is working on a fix (should be a pretty quick fix).

https://github.com/ohmage/server/wiki/Survey-Manipulation#survey-response-delete

**Comment by hongsudt** [comment] 2015-08-11 22:00
@wrenr This problem should be fixed now.  Can you retry?

**Comment by wrenr** [comment] 2015-08-11 22:50
fixed now, pushed functioning delete button

**Comment by ctrance** [comment] 2015-08-12 15:01
History's delete survey response is working good now.

**Closed by ctrance** 2015-08-12 15:01 UTC
Labels: Server Issue, Test
